### ISSUE TITLE
want the datasets

### ISSUE THREAD

**Issue by ZihaoZheng98** [Multimodal-NER/RpBERT#1]
Hi, I want to follow this work, can you send me the complete source code plus datasets to me?Thanks!

**Comment by edwhelloworld** [comment]
me too

**Comment by seanPudding** [comment]
me too

**Comment by zengzerong** [comment]
me too, may I ask whether you had got the dadasets? @ZihaoZheng98 @edwhelloworld @seanPudding

**Comment by HHHHedy** [comment]
Can you tell me where I can get these datasets?

**Comment by seanPudding** [comment]
The text portion of the img-txt classification dataset and the NER dataset can be found in the references, and the image portion of the img-txt classification dataset in the:
https://www.dropbox.com/s/olkxuw8b9cy9i0q/Twitter_images.zip?dl=0
snap dataset：
https://urldefense.proofpoint.com/v2/url?u=https-3A__www.dropbox.com_s_pd1vakhl4hiyfe8_Twitter-5Fdatasets.tar.gz-3Fdl-3D0&d=DwMFAg&c=ncDTmphkJTvjIDPh0hpF_w&r=jrqKEl_yfpiP73TVOogW5A&m=gaZNWv7ktw8EF12vizEnHweCj-YguMeibD2-UdZaeYw&s=xBYDATNakNStRh5Wabn-RswsbUDvsoB3hUafPyGNKD8&e=
Some pre-processing of the dataset is required to make the code work correctly

**Comment by gagaein** [comment]
Thank you for your work!
I am trying to repeat your paper and need to use TRC dataset. You have kindly provide its images from https://www.dropbox.com/s/olkxuw8b9cy9i0q/Twitter_images.zip?dl=0
And I get text from the .csv file in this project https://github.com/danielpreotiuc/text-image-relationship.
But they seem to not match. Can you give me a hand?
Thank you again!

**Comment by terence1023** [comment]
> The text portion of the img-txt classification dataset and the NER dataset can be found in the references, and the image portion of the img-txt classification dataset in the: https://www.dropbox.com/s/olkxuw8b9cy9i0q/Twitter_images.zip?dl=0 snap dataset： https://urldefense.proofpoint.com/v2/url?u=https-3A__www.dropbox.com_s_pd1vakhl4hiyfe8_Twitter-5Fdatasets.tar.gz-3Fdl-3D0&d=DwMFAg&c=ncDTmphkJTvjIDPh0hpF_w&r=jrqKEl_yfpiP73TVOogW5A&m=gaZNWv7ktw8EF12vizEnHweCj-YguMeibD2-UdZaeYw&s=xBYDATNakNStRh5Wabn-RswsbUDvsoB3hUafPyGNKD8&e= Some pre-processing of the dataset is required to make the code work correctly

This link has no Snap dataset "https://urldefense.proofpoint.com/v2/url?u=https-3A__www.dropbox.com_s_pd1vakhl4hiyfe8_Twitter-5Fdatasets.tar.gz-3Fdl-3D0&d=DwMFAg&c=ncDTmphkJTvjIDPh0hpF_w&r=jrqKEl_yfpiP73TVOogW5A&m=gaZNWv7ktw8EF12vizEnHweCj-YguMeibD2-UdZaeYw&s=xBYDATNakNStRh5Wabn-RswsbUDvsoB3hUafPyGNKD8&e=". Could you provide a new link? Thank you very much!

**Comment by Cloriaaaaa12** [comment]
> 感谢您的工作！ 我正在尝试重复您的论文，需要使用 TRC 数据集。您好心地从[https://www.dropbox.com/s/olkxuw8b9cy9i0q/Twitter_images.zip?dl=0提供了其图像，我从该项目](https://www.dropbox.com/s/olkxuw8b9cy9i0q/Twitter_images.zip?dl=0)https://github.com/danielpreotiuc/text-image-relationship 中的 .csv 文件中获取了文本。 但它们似乎不匹配。您能帮我一下吗？ 再次感谢您！[](https://github.com/danielpreotiuc/text-image-relationship)

The same question, how did you solve it? thank you
