### ISSUE TITLE
Cannot get the reported performance

### ISSUE THREAD

**Issue by JZXXX** [Multimodal-NER/RpBERT#3]
Hi, I am confused that I run this code with all required datasets and tools, but I cannot get the reported performance. The performance gap is so large, so I think there are some mistakes, but I did not change the code, and I cannot find what is wrong. Could you help to provide some checkpoints or give some suggestions?

**Comment by 10652835** [comment]
I only get the F1 value of 66.1 on the Fudan dataset. Is the result you get similar to mine? I wonder if there is something wrong with me?

**Comment by JZXXX** [comment]
Yes, I get the similar performance. I have not solved it.

**Comment by SuYindu** [comment]
@JZXXX @XGBao We have fixed the problem and get the reported performance.
